# Generated by Django 5.0 on 2025-12-30 11:00

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        VectorExtension()
    ]
